name: dating
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  page_view_indicators: ^1.3.1
  shared_preferences: ^0.5.6
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.6
  image_picker: ^0.6.5
  firebase_storage: ^3.1.5
  progress_dialog: ^1.2.2
  provider: ^4.0.1
  url_launcher: ^3.0.1
  intl: ^0.16.1
  cached_network_image: ^2.1.0+1
  uuid: ^2.0.4
  video_thumbnail: ^0.2.1
  path_provider: ^1.6.7
  photo_view: ^0.9.2
  video_player: ^0.10.9+1
  flutter_facebook_login: ^3.0.0
  http: ^0.12.1
  location: ^3.0.0
  latlong: ^0.6.1
  smooth_page_indicator: ^0.1.5
  flutter_webrtc: ^0.2.8
  firebase_messaging: ^6.0.16
  intl_phone_number_input: ^0.4.6+2
  pin_code_fields: ^3.1.2
  in_app_purchase: ^0.3.4+1
  flutter_ringtone_player: ^2.0.0
  wakelock: ^0.1.4+1
  audio_recorder: ^1.0.2
  audioplayers: ^0.15.1
  permission_handler: ^5.0.1+1

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
